version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "${DB_PORT}:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - mongo
  #   env_file:
  #     - .env
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_BASICAUTH_USERNAME: admin
  #     ME_CONFIG_BASICAUTH_PASSWORD: admin123

  config_server:
    build:
      context: ./config_server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - url_shortener_network

  discovery_server:
    build:
      context: ./discovery_server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - url_shortener_network

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - url_shortener_network
    depends_on:
      - config_server
      - discovery_server

  shortener_service:
    build:
      context: ./url_shortener/shortener_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - url_shortener_network
    depends_on:
      config_server:
        condition: service_started
      discovery_server:
        condition: service_started
      mongo:
        condition: service_started
      

volumes:
  mongo_data:
    driver: local

networks:
  url_shortener_network:
    driver: bridge