#spring.application.name=shortener_service
#server.port=3000
#spring.data.mongodb.uri=mongodb://root:rootpw@localhost:5432/urlshortenerdb?authSource=admin
#
##server.error.whitelabel.enabled=false
##server.error.path=/error
#
##server.error.whitelabel.enabled=false
##server.error.include-stacktrace=always
#server.error.include-message=always
#
#springdoc.swagger-ui.path=/api-docs.html
#
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always

server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: shortener-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true