server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: redirection_service
  data:
    mongodb:
      uri: mongodb://root:rootpw@localhost:5432/urlshortenerdb?authSource=admin