server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/belalmoh/url_shortener_config_repo
          search-paths: '{profile}'
      override-system-properties: false